
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 37
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 65
#define YY_END_OF_BUFFER 66
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_acclist[446] =
    {   0,
       35,   35,   66,   64,   65,   63,   64,   65,   62,   63,
       65,   52,   64,   65,   34,   64,   65,   42,   64,   65,
       64,   65,   58,   64,   65,   59,   64,   65,   40,   64,
       65,   38,   64,   65,   54,   64,   65,   39,   64,   65,
       55,   64,   65,   41,   64,   65,   28,   64,   65,   28,
       64,   65,   53,   64,   65,   43,   64,   65,   47,   64,
       65,   45,   64,   65,   32,   64,   65,16417,   32,   64,
       65,16417,   32,   64,   65,16417,   32,   64,   65,16417,
       56,   64,   65,   57,   64,   65,   32,   64,   65,16417,
       32,   64,   65,16417,   32,   64,   65,16417,   32,   64,

       65,16417,   32,   64,   65,16417,   32,   64,   65,16417,
       32,   64,   65,16417,   32,   64,   65,16417,   32,   64,
       65,16417,   32,   64,   65,16417,   32,   64,   65,16417,
       32,   64,   65,16417,   60,   64,   65,   64,   65,   61,
       64,   65,   35,   65,   36,   65,   37,   65,   65,    3,
       65,    4,   65,    3,   65,   49,   50,    1,   31,   28,
       44,   48,   46,   32,16417,   32,16417,   32,16417,   32,
    16417,   32,16417,   32,16417,   32,16417,   32,16417,   32,
    16417,   32,16417,   32,16417,   32,16417,   19,   32,16417,
       32,16417,   32,16417,   32,16417,   32,16417,   32,16417,

       32,16417,   32,16417,   32,16417,   32,16417,   51,   35,
        2,    5,   31,   28, 8225,   23,   32,16417,   32,16417,
       32,16417,   32,16417,   32,16417,   32,16417,   32,16417,
       32,16417,   32,16417,   32,16417,   17,   32,16417,   32,
    16417,    7,   32,16417,   32,16417,   32,16417,   32,16417,
       32,16417,   32,16417,   32,16417,   32,16417,   31,   32,
    16417,   32,16417,   32,16417,    9,   32,16417,   32,16417,
       32,16417,   32,16417,   20,   32,16417,   32,16417,   32,
    16417,   19, 8225,   32,16417,   32,16417,   13,   32,16417,
       32,16417,   32,16417,   14,   32,16417,   29,   32,16417,

        6,   32,16417,   32,16417,   23, 8225,   32,16417,   25,
       32,16417,   32,16417,   32,16417,   22,   32,16417,   11,
       32,16417,   32,16417,   32,16417,   30,   32,16417,   17,
     8225,   32,16417,    7, 8225,   32,16417,   32,16417,   32,
    16417,   18,   32,16417,   32,16417,   32,16417,   32,16417,
        9, 8225,    8,   32,16417,   20, 8225,   32,16417,   32,
    16417,   32,16417,   13, 8225,   21,   32,16417,   10,   32,
    16417,   14, 8225,   29, 8225,    6, 8225,   32,16417,   25,
     8225,   32,16417,   32,16417,   22, 8225,   11, 8225,   15,
       32,16417,   30, 8225,   32,16417,   32,16417,   18, 8225,

       24,   32,16417,   32,16417,   27,   32,16417,    8, 8225,
       32,16417,   32,16417,   21, 8225,   10, 8225,   32,16417,
       15, 8225,   32,16417,   12,   32,16417,   24, 8225,   32,
    16417,   27, 8225,   16,   32,16417,   26,   32,16417,   12,
     8225,   16, 8225,   26, 8225
    } ;

static yyconst flex_int16_t yy_accept[282] =
    {   0,
        1,    1,    1,    2,    3,    3,    3,    3,    3,    4,
        6,    9,   12,   15,   18,   21,   23,   26,   29,   32,
       35,   38,   41,   44,   47,   50,   53,   56,   59,   62,
       65,   69,   73,   77,   81,   84,   87,   91,   95,   99,
      103,  107,  111,  115,  119,  123,  127,  131,  135,  138,
      140,  143,  145,  147,  149,  150,  152,  154,  156,  157,
      158,  159,  159,  160,  161,  161,  162,  163,  164,  164,
      166,  166,  168,  170,  172,  174,  176,  178,  180,  182,
      184,  186,  188,  191,  193,  195,  197,  199,  201,  203,
      205,  207,  209,  210,  211,  212,  212,  213,  214,  214,

      215,  216,  216,  219,  221,  223,  225,  227,  229,  231,
      233,  235,  237,  240,  240,  240,  242,  245,  247,  249,
      251,  253,  255,  257,  259,  259,  260,  260,  262,  262,
      264,  266,  269,  271,  273,  275,  278,  280,  282,  282,
      282,  284,  284,  286,  286,  286,  288,  291,  293,  295,
      298,  301,  304,  306,  308,  310,  310,  313,  315,  317,
      317,  317,  320,  323,  325,  325,  325,  327,  330,  332,
      332,  334,  336,  336,  338,  338,  338,  340,  342,  342,
      342,  342,  342,  342,  342,  345,  347,  347,  347,  349,
      351,  353,  353,  353,  353,  353,  353,  356,  358,  358,

      360,  360,  360,  362,  364,  366,  366,  369,  372,  374,
      374,  376,  376,  378,  378,  378,  378,  380,  382,  382,
      384,  386,  388,  388,  390,  390,  390,  390,  393,  395,
      395,  397,  399,  399,  399,  399,  399,  401,  401,  404,
      406,  409,  411,  411,  411,  411,  413,  415,  417,  417,
      419,  419,  419,  419,  421,  421,  421,  423,  423,  425,
      428,  430,  430,  432,  434,  434,  437,  437,  437,  440,
      440,  440,  442,  442,  442,  442,  444,  444,  446,  446,
      446
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    1,    1,    6,    7,    1,    8,
        9,   10,   11,   12,   13,   14,   15,   16,   17,   17,
       17,   17,   17,   17,   17,   17,   17,    1,   18,   19,
       20,   21,    1,    1,   22,   23,   23,   23,   24,   23,
       25,   25,   26,   25,   25,   27,   25,   28,   25,   29,
       25,   30,   25,   25,   25,   25,   25,   31,   25,   25,
       32,    1,   33,    1,   34,    1,   35,   36,   37,   38,

       39,   40,   41,   42,   43,   25,   44,   45,   46,   47,
       48,   49,   25,   50,   51,   52,   53,   54,   55,   56,
       57,   25,   58,   59,   60,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[61] =
    {   0,
        1,    2,    3,    1,    4,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    5,    5,    1,    1,    1,
        1,    6,    6,    6,    2,    2,    2,    2,    2,    2,
        2,    2,    1,    7,    6,    6,    6,    6,    6,    6,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    1,    1,    1
    } ;

static yyconst flex_int16_t yy_base[313] =
    {   0,
        0,    0,   58,   59,    0,    0,   62,   63,  120, 1112,
     1112, 1112,   97, 1112, 1112,  105, 1112, 1112, 1112, 1112,
     1112, 1112, 1112,   59,   54,   61, 1112,   88,   85,   78,
       77,   79,   81,   84, 1112, 1112,   87,   89,   92,   94,
       97,  101,  104,  112,  140,  151,  156,  153, 1112,   34,
     1112,    0, 1112, 1112, 1112, 1112, 1112,   73, 1112, 1112,
     1112,   73,  145,  111,    0, 1112, 1112, 1112,  162,  164,
      172,  168,  174,  176,  178,  188,  184,  196,  200,  210,
      212,  222,  227,  231,  233,  236,  238,  243,  245,  250,
      264,  276, 1112,    0, 1112,   64, 1112,  267,  281,    0,

     1112,  253,  298,  302,  307,  309,  311,  315,  319,  321,
      324,  326,  329,  333,  335,  367,  369,  371,  373,  377,
      379,  382,  385,  387,   85,  205,  390,  392,  394,  404,
      426,  431,  435,  437,  441,  443,  445,  448,  452,  457,
     1112,  462,  459,  468,  479,  491,  494,  499,  501,  503,
      505,  507,  511, 1112,  513,  518,  515,  522,  525,  527,
      550,  553,  558,  562,  564,  569,  571,  573, 1112,  575,
      578, 1112,  584,  586,  589,  595,  597,  604,  609,  613,
      611,  617,  620,  628,  630,  632,  636,  645,  651,  653,
     1112,  655,  657,  663,  667,  669,  672, 1112,  674,  677,

      679,  684,  688,  690, 1112,  703,  692,  710, 1112,  712,
     1112,  716, 1112,  727,  729,  731,  735, 1112,  737,  741,
      744, 1112,  748, 1112,  751,  753,  755,  763, 1112,  760,
      766,  769,  772,  775,  784,  787, 1112,  794,  797,  800,
      807, 1112,  809,  812,  815,  819,  821, 1112,  823, 1112,
      828,  831,  833,  835,  843,  847, 1112,  852,  855,  862,
     1112,  866,  870, 1112,  874,  876,  879,  881,  886,  889,
      893, 1112,  895,  898,  901, 1112,  907, 1112,  910, 1112,
      943,  950,  957,  963,  970,  977,  980,  985,  990,  995,
     1000, 1005, 1010, 1015, 1020, 1025, 1030, 1035, 1040, 1045,

     1050, 1055, 1060, 1065, 1070, 1075, 1080, 1085, 1090, 1095,
     1100, 1105
    } ;

static yyconst flex_int16_t yy_def[313] =
    {   0,
      280,    1,  281,  281,  282,  282,  283,  283,  280,  280,
      280,  280,  280,  280,  280,  280,  280,  280,  280,  280,
      280,  280,  280,  280,  280,  280,  280,  280,  280,  280,
      284,  284,  284,  284,  280,  280,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  280,  280,
      280,  285,  280,  280,  280,  280,  280,  280,  280,  280,
      280,  286,  280,  280,  287,  280,  280,  280,  288,  284,
      280,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  280,  285,  280,  286,  280,  280,  280,  287,

      280,  280,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  289,  280,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  280,  280,  290,  284,  280,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  291,  280,
      280,  280,  284,  292,  280,  284,  284,  284,  284,  284,
      284,  284,  284,  280,  284,  280,  284,  284,  284,  293,
      280,  284,  284,  284,  294,  280,  284,  284,  280,  280,
      284,  280,  280,  284,  295,  280,  284,  284,  296,  280,
      297,  280,  298,  280,  284,  284,  299,  280,  284,  284,
      280,  280,  300,  280,  301,  280,  284,  280,  280,  284,

      302,  280,  284,  284,  280,  280,  284,  284,  280,  280,
      280,  280,  280,  280,  303,  280,  284,  280,  280,  284,
      284,  280,  280,  280,  280,  304,  280,  284,  280,  280,
      284,  284,  305,  280,  306,  280,  280,  280,  284,  284,
      284,  280,  280,  307,  280,  284,  284,  280,  280,  280,
      280,  308,  280,  284,  309,  280,  280,  280,  284,  284,
      280,  280,  284,  280,  280,  284,  310,  280,  284,  311,
      280,  280,  280,  312,  280,  280,  280,  280,  280,    0,
      280,  280,  280,  280,  280,  280,  280,  280,  280,  280,
      280,  280,  280,  280,  280,  280,  280,  280,  280,  280,

      280,  280,  280,  280,  280,  280,  280,  280,  280,  280,
      280,  280
    } ;

static yyconst flex_int16_t yy_nxt[1173] =
    {   0,
       10,   11,   12,   13,   14,   15,   16,   17,   18,   19,
       20,   21,   22,   23,   24,   25,   26,   27,   28,   29,
       30,   31,   31,   31,   31,   31,   31,   32,   33,   34,
       31,   35,   36,   10,   31,   37,   38,   39,   40,   41,
       31,   31,   42,   31,   31,   31,   43,   31,   31,   44,
       45,   46,   31,   47,   48,   31,   31,   49,   50,   51,
       53,   53,   54,   54,   57,   57,   97,   63,   61,   64,
       64,   58,   58,   62,   63,   97,   64,   64,   69,   69,
       69,   69,   69,   69,   65,   69,   69,   95,   69,   69,
       69,   69,   93,   69,   69,   69,   69,   68,   69,   69,

      126,  126,   69,   69,   67,   69,   69,   66,   71,   65,
       71,   60,   71,   69,   69,   71,   59,   72,   71,  280,
       71,  280,   74,   71,   63,   71,   64,   64,   71,  280,
       73,   81,   71,   77,   75,   71,   76,  280,   79,   78,
       83,   69,   69,   71,   82,  280,   84,   85,  280,   80,
       87,  280,   69,   69,   69,   69,   86,   69,   69,  280,
       98,   98,  280,   69,   69,   69,   69,  280,   99,   69,
       69,   71,  280,  102,  102,   69,   69,   69,   69,   69,
       69,  280,   71,   99,   71,   69,   69,   71,  280,   69,
       69,   88,   89,   71,   92,   71,  280,   69,   69,   71,

       90,   69,   69,   91,  101,   71,  280,   71,  280,   71,
      105,   69,   69,   69,   69,   71,  104,  280,  108,   71,
      126,  126,  103,   69,   69,  106,  107,   71,  114,  114,
      280,   71,   69,   69,   69,   69,  280,   69,   69,   69,
       69,   71,  280,   71,   69,   69,   69,   69,  109,  280,
      110,   69,   69,   71,  102,  102,  112,  280,  115,  280,
      280,  111,   71,  280,   71,   69,   69,   71,  280,   71,
      280,  113,  280,  280,   71,  280,   71,   69,   69,  116,
      118,   71,   98,   98,  117,  101,  280,  121,  280,  119,
       99,  125,  120,  125,  280,   71,  126,  126,  280,  127,

      127,  280,  122,   69,   69,   99,  123,   71,   69,   69,
       69,   69,   69,   69,  280,  280,   69,   69,  124,  128,
       69,   69,   69,   69,  280,   69,   69,   69,   69,  129,
      139,  139,  280,   71,  114,  114,  142,  142,   71,  280,
       71,  280,   71,  280,  131,  133,   71,  280,  130,  280,
       71,  280,   71,  132,  135,   71,  280,   71,  280,  136,
      140,  280,  137,  280,  115,  134,  280,  141,   69,   69,
      144,  144,   69,   69,   69,   69,  138,  280,   69,   69,
       69,   69,  280,   69,   69,  280,   69,   69,   69,   69,
      280,  127,  127,   69,   69,  156,  156,  280,   71,  280,

      145,  280,   71,  280,   71,   69,   69,  146,   71,  280,
       71,  143,  280,   71,  280,  147,   71,  280,   71,  149,
      151,  129,  152,   71,  280,  148,  154,   69,   69,  150,
      280,  153,  160,  160,  280,   71,   69,   69,   69,   69,
      280,  155,   69,   69,  165,  165,   69,   69,  280,   69,
       69,  158,  159,  139,  139,  157,  280,   71,  170,  170,
       69,   69,  161,  142,  142,  280,   71,  280,   71,  144,
      144,  280,   71,  280,  166,  280,   71,  280,  162,   71,
      173,  173,  280,  140,  280,  164,  168,  163,  280,  169,
       71,  167,   69,   69,  141,  175,  175,  171,  280,  145,

       69,   69,   69,   69,  179,  179,  181,  181,  183,  183,
      280,  172,   69,   69,   69,   69,  187,  187,  280,  156,
      156,  280,   71,   69,   69,  176,   69,   69,  160,  160,
       71,  280,   71,  280,  180,  280,  182,  280,  184,  280,
      174,  280,   71,  280,   71,  280,  188,  178,  177,  185,
      154,  192,  192,   71,  193,  193,   71,  280,  161,  195,
      195,  280,  186,   69,   69,  165,  165,  190,  189,  280,
      199,  199,   69,   69,  201,  201,  170,  170,  280,   69,
       69,  280,  191,  280,  194,  173,  173,   69,   69,  196,
      175,  175,  280,   71,  280,  166,  206,  206,   69,   69,

      197,  198,   71,  280,  202,   69,   69,  169,  200,   71,
      179,  179,  181,  181,  210,  210,  172,   71,  212,  212,
      176,  183,  183,  203,  280,  204,  280,  205,   71,  214,
      214,  215,  215,   69,   69,   71,  280,  187,  187,  280,
      180,  280,  182,  207,  208,  209,  219,  219,  280,  211,
      280,  184,   69,   69,   69,   69,  192,  192,  193,  193,
      213,  216,  280,   71,  223,  223,  217,  188,  195,  195,
      225,  225,  280,  226,  226,  199,  199,  218,   69,   69,
      201,  201,   71,  280,   71,  230,  230,  191,  194,   69,
       69,   69,   69,  233,  233,  222,  280,  280,  196,  221,

      280,  224,  220,  227,  206,  206,  198,  280,   71,  280,
      202,  235,  235,  210,  210,  280,  229,  212,  212,   71,
      280,   71,  280,  234,  232,  280,  231,  228,  214,  214,
      215,  215,  238,  238,  280,  205,   69,   69,  219,  219,
      280,  236,   69,   69,  209,   69,   69,  280,  211,  223,
      223,  280,  225,  225,  226,  226,  243,  243,  280,  213,
      216,  230,  230,  237,  244,  244,   71,   69,   69,  218,
       69,   69,   71,  233,  233,   71,  249,  249,  280,  240,
      222,  280,  241,  224,  227,  235,  235,  242,  251,  251,
      280,  239,  229,  280,  245,  238,  238,   71,  252,  252,

       71,   69,   69,  234,  280,  247,  280,  248,  255,  255,
      243,  243,  246,  244,  244,  236,  258,  258,  280,  250,
       69,   69,   69,   69,  249,  249,  237,  280,  253,  251,
      251,   71,  252,  252,  262,  262,   69,   69,  256,  280,
      254,  242,  280,  245,  255,  255,  280,  257,  265,  265,
       71,  280,   71,  258,  258,  248,   69,   69,  280,  260,
      250,  280,  253,  267,  267,  261,   71,  262,  262,  280,
      259,   69,   69,  263,  256,  265,  265,  270,  270,  264,
      267,  267,  273,  273,  257,  280,   71,  274,  274,  280,
      270,  270,  280,  268,  277,  277,  273,  273,  261,  274,

      274,   71,  279,  279,  280,  266,  264,  271,  277,  277,
      268,  279,  279,  272,  280,  280,  280,  275,  280,  269,
      271,  280,  280,  280,  280,  276,  280,  272,  280,  275,
      280,  280,  280,  278,  280,  280,  280,  280,  280,  276,
      280,  280,  278,   52,   52,   52,   52,   52,   52,   52,
       55,   55,   55,   55,   55,   55,   55,   56,   56,   56,
       56,   56,   56,   56,   70,   70,  280,   70,   70,   70,
       94,   94,  280,  280,   94,   94,   94,   96,   96,   96,
       96,   96,   96,   96,  100,  100,  101,  101,  280,  280,
      101,  141,  141,  280,  280,  141,  154,  154,  280,  280,

      154,  169,  169,  280,  280,  169,  172,  172,  280,  280,
      172,  191,  191,  280,  280,  191,  198,  198,  280,  280,
      198,  205,  205,  280,  280,  205,  209,  209,  280,  280,
      209,  211,  211,  280,  280,  211,  213,  213,  280,  280,
      213,  218,  218,  280,  280,  218,  222,  222,  280,  280,
      222,  224,  224,  280,  280,  224,  229,  229,  280,  280,
      229,  237,  237,  280,  280,  237,  242,  242,  280,  280,
      242,  248,  248,  280,  280,  248,  250,  250,  280,  280,
      250,  257,  257,  280,  280,  257,  261,  261,  280,  280,
      261,  264,  264,  280,  280,  264,  272,  272,  280,  280,

      272,  276,  276,  280,  280,  276,  278,  278,  280,  280,
      278,    9,  280,  280,  280,  280,  280,  280,  280,  280,
      280,  280,  280,  280,  280,  280,  280,  280,  280,  280,
      280,  280,  280,  280,  280,  280,  280,  280,  280,  280,
      280,  280,  280,  280,  280,  280,  280,  280,  280,  280,
      280,  280,  280,  280,  280,  280,  280,  280,  280,  280,
      280,  280,  280,  280,  280,  280,  280,  280,  280,  280,
      280,  280
    } ;

static yyconst flex_int16_t yy_chk[1173] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        3,    4,    3,    4,    7,    8,   96,   25,   24,   25,
       25,    7,    8,   24,   26,   62,   26,   26,   31,   31,
       32,   32,   33,   33,   25,   34,   34,   58,   37,   37,
       38,   38,   50,   39,   39,   40,   40,   30,   41,   41,

      125,  125,   42,   42,   29,   43,   43,   28,   31,   25,
       32,   16,   33,   44,   44,   34,   13,   32,   37,    9,
       38,    0,   34,   39,   64,   40,   64,   64,   41,    0,
       33,   41,   42,   38,   37,   43,   37,    0,   40,   39,
       42,   45,   45,   44,   41,    0,   42,   42,    0,   40,
       44,    0,   46,   46,   48,   48,   43,   47,   47,    0,
       63,   63,    0,   69,   69,   70,   70,    0,   63,   72,
       72,   45,    0,   71,   71,   73,   73,   74,   74,   75,
       75,    0,   46,   63,   48,   77,   77,   47,    0,   76,
       76,   45,   46,   69,   48,   70,    0,   78,   78,   72,

       46,   79,   79,   47,   71,   73,    0,   74,    0,   75,
       74,   80,   80,   81,   81,   77,   73,    0,   77,   76,
      126,  126,   72,   82,   82,   75,   76,   78,   83,   83,
        0,   79,   84,   84,   85,   85,    0,   86,   86,   87,
       87,   80,    0,   81,   88,   88,   89,   89,   78,    0,
       79,   90,   90,   82,  102,  102,   81,    0,   83,    0,
        0,   80,   84,    0,   85,   91,   91,   86,    0,   87,
        0,   82,    0,    0,   88,    0,   89,   92,   92,   84,
       86,   90,   98,   98,   85,  102,    0,   89,    0,   87,
       98,   99,   88,   99,    0,   91,   99,   99,    0,  103,

      103,    0,   90,  104,  104,   98,   91,   92,  105,  105,
      106,  106,  107,  107,    0,    0,  108,  108,   92,  103,
      109,  109,  110,  110,    0,  111,  111,  112,  112,  103,
      113,  113,    0,  104,  114,  114,  115,  115,  105,    0,
      106,    0,  107,    0,  105,  107,  108,    0,  104,    0,
      109,    0,  110,  106,  109,  111,    0,  112,    0,  110,
      113,    0,  111,    0,  114,  108,    0,  115,  116,  116,
      117,  117,  118,  118,  119,  119,  112,    0,  120,  120,
      121,  121,    0,  122,  122,    0,  123,  123,  124,  124,
        0,  127,  127,  128,  128,  129,  129,    0,  116,    0,

      117,    0,  118,    0,  119,  130,  130,  117,  120,    0,
      121,  116,    0,  122,    0,  118,  123,    0,  124,  120,
      122,  127,  123,  128,    0,  119,  129,  131,  131,  121,
        0,  124,  132,  132,    0,  130,  133,  133,  134,  134,
        0,  128,  135,  135,  136,  136,  137,  137,    0,  138,
      138,  131,  131,  139,  139,  130,    0,  131,  140,  140,
      143,  143,  132,  142,  142,    0,  133,    0,  134,  144,
      144,    0,  135,    0,  136,    0,  137,    0,  133,  138,
      145,  145,    0,  139,    0,  135,  138,  134,    0,  140,
      143,  137,  146,  146,  142,  147,  147,  143,    0,  144,

      148,  148,  149,  149,  150,  150,  151,  151,  152,  152,
        0,  145,  153,  153,  155,  155,  157,  157,    0,  156,
      156,    0,  146,  158,  158,  147,  159,  159,  160,  160,
      148,    0,  149,    0,  150,    0,  151,    0,  152,    0,
      146,    0,  153,    0,  155,    0,  157,  149,  148,  153,
      156,  161,  161,  158,  162,  162,  159,    0,  160,  163,
      163,    0,  155,  164,  164,  165,  165,  159,  158,    0,
      166,  166,  167,  167,  168,  168,  170,  170,    0,  171,
      171,    0,  161,    0,  162,  173,  173,  174,  174,  163,
      175,  175,    0,  164,    0,  165,  176,  176,  177,  177,

      164,  166,  167,    0,  168,  178,  178,  170,  167,  171,
      179,  179,  181,  181,  180,  180,  173,  174,  182,  182,
      175,  183,  183,  171,    0,  174,    0,  176,  177,  184,
      184,  185,  185,  186,  186,  178,    0,  187,  187,    0,
      179,    0,  181,  177,  178,  180,  188,  188,    0,  182,
        0,  183,  189,  189,  190,  190,  192,  192,  193,  193,
      184,  185,    0,  186,  194,  194,  186,  187,  195,  195,
      196,  196,    0,  197,  197,  199,  199,  188,  200,  200,
      201,  201,  189,    0,  190,  202,  202,  192,  193,  203,
      203,  204,  204,  207,  207,  194,    0,    0,  195,  190,

        0,  196,  189,  197,  206,  206,  199,    0,  200,    0,
      201,  208,  208,  210,  210,    0,  202,  212,  212,  203,
        0,  204,    0,  207,  204,    0,  203,  200,  214,  214,
      215,  215,  216,  216,    0,  206,  217,  217,  219,  219,
        0,  208,  220,  220,  210,  221,  221,    0,  212,  223,
      223,    0,  225,  225,  226,  226,  227,  227,    0,  214,
      215,  230,  230,  216,  228,  228,  217,  231,  231,  219,
      232,  232,  220,  233,  233,  221,  234,  234,    0,  220,
      223,    0,  221,  225,  226,  235,  235,  227,  236,  236,
        0,  217,  230,    0,  228,  238,  238,  231,  239,  239,

      232,  240,  240,  233,    0,  232,    0,  234,  241,  241,
      243,  243,  231,  244,  244,  235,  245,  245,    0,  236,
      246,  246,  247,  247,  249,  249,  238,    0,  239,  251,
      251,  240,  252,  252,  253,  253,  254,  254,  241,    0,
      240,  243,    0,  244,  255,  255,    0,  245,  256,  256,
      246,    0,  247,  258,  258,  249,  259,  259,    0,  247,
      251,    0,  252,  260,  260,  253,  254,  262,  262,    0,
      246,  263,  263,  254,  255,  265,  265,  266,  266,  256,
      267,  267,  268,  268,  258,    0,  259,  269,  269,    0,
      270,  270,    0,  260,  271,  271,  273,  273,  262,  274,

      274,  263,  275,  275,    0,  259,  265,  266,  277,  277,
      267,  279,  279,  268,    0,    0,    0,  269,    0,  263,
      270,    0,    0,    0,    0,  271,    0,  273,    0,  274,
        0,    0,    0,  275,    0,    0,    0,    0,    0,  277,
        0,    0,  279,  281,  281,  281,  281,  281,  281,  281,
      282,  282,  282,  282,  282,  282,  282,  283,  283,  283,
      283,  283,  283,  283,  284,  284,    0,  284,  284,  284,
      285,  285,    0,    0,  285,  285,  285,  286,  286,  286,
      286,  286,  286,  286,  287,  287,  288,  288,    0,    0,
      288,  289,  289,    0,    0,  289,  290,  290,    0,    0,

      290,  291,  291,    0,    0,  291,  292,  292,    0,    0,
      292,  293,  293,    0,    0,  293,  294,  294,    0,    0,
      294,  295,  295,    0,    0,  295,  296,  296,    0,    0,
      296,  297,  297,    0,    0,  297,  298,  298,    0,    0,
      298,  299,  299,    0,    0,  299,  300,  300,    0,    0,
      300,  301,  301,    0,    0,  301,  302,  302,    0,    0,
      302,  303,  303,    0,    0,  303,  304,  304,    0,    0,
      304,  305,  305,    0,    0,  305,  306,  306,    0,    0,
      306,  307,  307,    0,    0,  307,  308,  308,    0,    0,
      308,  309,  309,    0,    0,  309,  310,  310,    0,    0,

      310,  311,  311,    0,    0,  311,  312,  312,    0,    0,
      312,  280,  280,  280,  280,  280,  280,  280,  280,  280,
      280,  280,  280,  280,  280,  280,  280,  280,  280,  280,
      280,  280,  280,  280,  280,  280,  280,  280,  280,  280,
      280,  280,  280,  280,  280,  280,  280,  280,  280,  280,
      280,  280,  280,  280,  280,  280,  280,  280,  280,  280,
      280,  280,  280,  280,  280,  280,  280,  280,  280,  280,
      280,  280
    } ;

extern int yy_flex_debug;
int yy_flex_debug = 0;

static yy_state_type *yy_state_buf=0, *yy_state_ptr=0;
static char *yy_full_match;
static int yy_lp;
static int yy_looking_for_trail_begin = 0;
static int yy_full_lp;
static int *yy_full_state;
#define YY_TRAILING_MASK 0x2000
#define YY_TRAILING_HEAD_MASK 0x4000
#define REJECT \
{ \
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */ \
yy_cp = (yy_full_match); /* restore poss. backed-over text */ \
(yy_lp) = (yy_full_lp); /* restore orig. accepting pos. */ \
(yy_state_ptr) = (yy_full_state); /* restore orig. state */ \
yy_current_state = *(yy_state_ptr); /* restore curr. state */ \
++(yy_lp); \
goto find_rule; \
}

#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "decaf.lex"
/* definitions */
#line 4 "decaf.lex"

#include <iostream>

using namespace std;

#include "tokentype.h"

string resultString;
int startline;
Token* myTok;

int lineno = 1;

int error(string msg, int line)
{
  cout << msg << " on line " << line << endl;
  return -1;
}

TokenType makeToken(TokenType type) {
    myTok = new Token(type, yytext, lineno);
    return type;
}

int ident_error(char * txt, int line) {
  cout << "identifier " << txt << " too long on line " << line << endl;
  return -1;
}

/* %option yylineno */



#line 909 "lex.yy.c"

#define INITIAL 0
#define STRING 1
#define ESC_CHAR 2
#define BCOMM 3

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 42 "decaf.lex"


  /* rules */

  /* block comment machine */
#line 1100 "lex.yy.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

        /* Create the reject buffer large enough to save one state per allowed character. */
        if ( ! (yy_state_buf) )
            (yy_state_buf) = (yy_state_type *)yyalloc(YY_STATE_BUF_SIZE  );
            if ( ! (yy_state_buf) )
                YY_FATAL_ERROR( "out of dynamic memory in yylex()" );

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);

		(yy_state_ptr) = (yy_state_buf);
		*(yy_state_ptr)++ = yy_current_state;

yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 281 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*(yy_state_ptr)++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1112 );

yy_find_action:
		yy_current_state = *--(yy_state_ptr);
		(yy_lp) = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( (yy_lp) && (yy_lp) < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[(yy_lp)];
				if ( yy_act & YY_TRAILING_HEAD_MASK ||
				     (yy_looking_for_trail_begin) )
					{
					if ( yy_act == (yy_looking_for_trail_begin) )
						{
						(yy_looking_for_trail_begin) = 0;
						yy_act &= ~YY_TRAILING_HEAD_MASK;
						break;
						}
					}
				else if ( yy_act & YY_TRAILING_MASK )
					{
					(yy_looking_for_trail_begin) = yy_act & ~YY_TRAILING_MASK;
					(yy_looking_for_trail_begin) |= YY_TRAILING_HEAD_MASK;
					}
				else
					{
					(yy_full_match) = yy_cp;
					(yy_full_state) = (yy_state_ptr);
					(yy_full_lp) = (yy_lp);
					break;
					}
				++(yy_lp);
				goto find_rule;
				}
			--yy_cp;
			yy_current_state = *--(yy_state_ptr);
			(yy_lp) = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
YY_RULE_SETUP
#line 47 "decaf.lex"
{ BEGIN(BCOMM); startline = lineno; }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 48 "decaf.lex"
{ BEGIN(INITIAL); }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 49 "decaf.lex"
{ }
	YY_BREAK
case 4:
/* rule 4 can match eol */
YY_RULE_SETUP
#line 50 "decaf.lex"
{ lineno++; }
	YY_BREAK
case YY_STATE_EOF(BCOMM):
#line 51 "decaf.lex"
{ return error("Missing */ for block comment starting", startline); }
	YY_BREAK
/* Single line comment */
case 5:
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 54 "decaf.lex"
{}
	YY_BREAK
/* keywords */
case 6:
/* rule 6 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp = yy_bp + 4;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 59 "decaf.lex"
{ return makeToken(T_Void); }
	YY_BREAK
case 7:
/* rule 7 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp = yy_bp + 3;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 60 "decaf.lex"
{ return makeToken(T_Int); }
	YY_BREAK
case 8:
/* rule 8 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp = yy_bp + 6;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 61 "decaf.lex"
{ return makeToken(T_Double); }
	YY_BREAK
case 9:
/* rule 9 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp = yy_bp + 4;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 62 "decaf.lex"
{ return makeToken(T_Bool); }
	YY_BREAK
case 10:
/* rule 10 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp = yy_bp + 6;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 63 "decaf.lex"
{ return makeToken(T_String); }
	YY_BREAK
case 11:
/* rule 11 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp = yy_bp + 5;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 64 "decaf.lex"
{ return makeToken(T_Class); }
	YY_BREAK
case 12:
/* rule 12 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp = yy_bp + 9;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 65 "decaf.lex"
{ return makeToken(T_Interface); }
	YY_BREAK
case 13:
/* rule 13 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp = yy_bp + 4;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 66 "decaf.lex"
{ return makeToken(T_Null); }
	YY_BREAK
case 14:
/* rule 14 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp = yy_bp + 4;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 67 "decaf.lex"
{ return makeToken(T_This); }
	YY_BREAK
case 15:
/* rule 15 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp = yy_bp + 7;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 68 "decaf.lex"
{ return makeToken(T_Extends); }
	YY_BREAK
case 16:
/* rule 16 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp = yy_bp + 10;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 69 "decaf.lex"
{ return makeToken(T_Implements); }
	YY_BREAK
case 17:
/* rule 17 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp = yy_bp + 3;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 70 "decaf.lex"
{ return makeToken(T_For); }
	YY_BREAK
case 18:
/* rule 18 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp = yy_bp + 5;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 71 "decaf.lex"
{ return makeToken(T_While); }
	YY_BREAK
case 19:
/* rule 19 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp = yy_bp + 2;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 72 "decaf.lex"
{ return makeToken(T_If); }
	YY_BREAK
case 20:
/* rule 20 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp = yy_bp + 4;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 73 "decaf.lex"
{ return makeToken(T_Else); }
	YY_BREAK
case 21:
/* rule 21 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp = yy_bp + 6;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 74 "decaf.lex"
{ return makeToken(T_Return); }
	YY_BREAK
case 22:
/* rule 22 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp = yy_bp + 5;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 75 "decaf.lex"
{ return makeToken(T_Break); }
	YY_BREAK
case 23:
/* rule 23 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp = yy_bp + 3;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 76 "decaf.lex"
{ return makeToken(T_New); }
	YY_BREAK
case 24:
/* rule 24 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp = yy_bp + 8;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 77 "decaf.lex"
{ return makeToken(T_NewArray); }
	YY_BREAK
case 25:
/* rule 25 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp = yy_bp + 5;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 78 "decaf.lex"
{ return makeToken(T_Print); }
	YY_BREAK
case 26:
/* rule 26 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp = yy_bp + 11;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 79 "decaf.lex"
{ return makeToken(T_ReadInteger); }
	YY_BREAK
case 27:
/* rule 27 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp = yy_bp + 8;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 80 "decaf.lex"
{ return makeToken(T_ReadLine); }
	YY_BREAK
/* Int constant */
case 28:
YY_RULE_SETUP
#line 83 "decaf.lex"
{ return makeToken(T_IntConstant); }
	YY_BREAK
/* Boolean constant */
case 29:
/* rule 29 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp = yy_bp + 4;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 86 "decaf.lex"
{ return makeToken(T_BoolConstant); }
	YY_BREAK
case 30:
/* rule 30 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp = yy_bp + 5;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 87 "decaf.lex"
{ return makeToken(T_BoolConstant); }
	YY_BREAK
/* Double Constant */
case 31:
YY_RULE_SETUP
#line 90 "decaf.lex"
{ return makeToken(T_DoubleConstant); }
	YY_BREAK
/* identifier */
case 32:
YY_RULE_SETUP
#line 93 "decaf.lex"
{ if (yyleng > 31) return ident_error(yytext, lineno); return makeToken(T_Identifier); }
	YY_BREAK
/* type ident */
case 33:
/* rule 33 can match eol */
YY_RULE_SETUP
#line 97 "decaf.lex"
{ return makeToken(T_TypeIdentifier); }
	YY_BREAK
/* string literal */
/* \"(.|\\.)*\"  { return makeToken(T_StringConstant); }  */
/* \"([^\"][\\.])*\"$ { return makeToken(T_StringConstant); } */
case 34:
YY_RULE_SETUP
#line 103 "decaf.lex"
{ BEGIN(STRING); resultString = "\"";  }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 104 "decaf.lex"
{ resultString += yytext; }
	YY_BREAK
case 36:
/* rule 36 can match eol */
YY_RULE_SETUP
#line 105 "decaf.lex"
{lineno++; return error("missing \" at end of string constant", 
		lineno-1); }
	YY_BREAK
case YY_STATE_EOF(STRING):
#line 107 "decaf.lex"
{return error("missing \" at end of string constant", 
		lineno); } 
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 109 "decaf.lex"
{ BEGIN(INITIAL); 
	         myTok = new Token(T_StringConstant,resultString + "\"", 
                                  lineno);
		 return T_StringConstant; }
	YY_BREAK
/* Operator tokens */
case 38:
YY_RULE_SETUP
#line 115 "decaf.lex"
{ return makeToken(T_Plus); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 116 "decaf.lex"
{ return makeToken(T_Minus); } 
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 117 "decaf.lex"
{ return makeToken(T_Times); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 118 "decaf.lex"
{ return makeToken(T_Div); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 119 "decaf.lex"
{ return makeToken(T_Mod); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 120 "decaf.lex"
{ return makeToken(T_Less); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 121 "decaf.lex"
{ return makeToken(T_LessEqual); }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 122 "decaf.lex"
{ return makeToken(T_Greater); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 123 "decaf.lex"
{ return makeToken(T_GreaterEqual); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 124 "decaf.lex"
{ return makeToken(T_Assign); }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 125 "decaf.lex"
{ return makeToken(T_Equal); }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 126 "decaf.lex"
{ return makeToken(T_NotEqual); }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 127 "decaf.lex"
{ return makeToken(T_And); }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 128 "decaf.lex"
{ return makeToken(T_Or); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 129 "decaf.lex"
{ return makeToken(T_Not); }
	YY_BREAK
/* Other tokens */
case 53:
YY_RULE_SETUP
#line 132 "decaf.lex"
{ return makeToken(T_Semicolon); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 133 "decaf.lex"
{ return makeToken(T_Comma); }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 134 "decaf.lex"
{ return makeToken(T_Dot); }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 135 "decaf.lex"
{ return makeToken(T_LBracket); }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 136 "decaf.lex"
{ return makeToken(T_RBracket); }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 137 "decaf.lex"
{ return makeToken(T_LParen); }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 138 "decaf.lex"
{ return makeToken(T_RParen); }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 139 "decaf.lex"
{ return makeToken(T_LBrace); }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 140 "decaf.lex"
{ return makeToken(T_RBrace); }
	YY_BREAK
/* Increment line no */
case 62:
/* rule 62 can match eol */
YY_RULE_SETUP
#line 143 "decaf.lex"
{ lineno++; }
	YY_BREAK
/* Ignore whitespace */
case 63:
/* rule 63 can match eol */
YY_RULE_SETUP
#line 146 "decaf.lex"
{}
	YY_BREAK
/* DELETE THIS EVENTUALLY OR THROW ERROR STRAY CHAR */
case 64:
YY_RULE_SETUP
#line 149 "decaf.lex"
{ std::string s = "stray '"; return error(s + yytext + '\'', lineno); }
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(ESC_CHAR):
#line 153 "decaf.lex"
{ return -1; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 155 "decaf.lex"
ECHO;
	YY_BREAK
#line 1674 "lex.yy.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	(yy_state_ptr) = (yy_state_buf);
	*(yy_state_ptr)++ = yy_current_state;

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 281 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*(yy_state_ptr)++ = yy_current_state;
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    
	register YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 281 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 280);
	if ( ! yy_is_jam )
		*(yy_state_ptr)++ = yy_current_state;

		return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register yy_size_t number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

    (yy_state_buf) = 0;
    (yy_state_ptr) = 0;
    (yy_full_match) = 0;
    (yy_lp) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    yyfree ( (yy_state_buf) );
    (yy_state_buf)  = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 155 "decaf.lex"



  /* subroutines */

int yywrap(void) {
    return 1;  // makes it stop at EOF.
} 

int main(int argc, char **argv) {
    int tok;
    /* Make sure there's a given file name */
    if (argc != 2) {
        cout << "USAGE: " << argv[0] << " FILE" << endl;
        exit(1);
    }       
    yyin = fopen(argv[1], "r");
    /* and that it exists and can be read */
    if (!yyin) {
        cout << argv[1] << ": No such file or file can't be opened for reading." 
             << endl;
        exit(1);
    }
    /* Read tokens until finished */
    while ((tok=yylex()) != -1)
        myTok->print();

    /* there's a warning without this */
    if (false)
      yyunput(0, 0);
}

