
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 37
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex. 
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 67
#define YY_END_OF_BUFFER 68
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_acclist[588] =
    {   0,
       35,   35,   68,   66,   67,   65,   66,   67,   65,   67,
       55,   66,   67,   29,   66,   67,   45,   66,   67,   66,
       67,   61,   66,   67,   62,   66,   67,   43,   66,   67,
       41,   66,   67,   57,   66,   67,   42,   66,   67,   58,
       66,   67,   44,   66,   67,   38,   66,   67,   38,   66,
       67,   56,   66,   67,   46,   66,   67,   50,   66,   67,
       48,   66,   67, 8219,   66,   67,16411,16412, 8219,   66,
       67,16411,16412, 8219,   66,   67,16411,16412, 8219,   66,
       67,16411,16412,   59,   66,   67,   60,   66,   67, 8219,
       66,   67,16411,16412, 8219,   66,   67,16411,16412, 8219,

       66,   67,16411,16412, 8219,   66,   67,16411,16412, 8219,
       66,   67,16411,16412, 8219,   66,   67,16411,16412, 8219,
       66,   67,16411,16412, 8219,   66,   67,16411,16412, 8219,
       66,   67,16411,16412, 8219,   66,   67,16411,16412, 8219,
       66,   67,16411,16412, 8219,   66,   67,16411,16412,   63,
       66,   67,   66,   67,   64,   66,   67,   35,   67,   36,
       67,   37,   67,   35,   67,    3,   67,    3,   67,   52,
       53,    1,   38,   47,   51,   49, 8219,16411,16412, 8219,
    16411,16412, 8219,16411,16412, 8219,16411,16412, 8219,16411,
    16412, 8219,16411,16412, 8219,16411,16412, 8219,16411,16412,

     8219,16411,16412, 8219,16411,16412, 8219,16411,16412, 8219,
    16411,16412,   18, 8219,16411,16412, 8219,16411,16412, 8219,
    16411,16412, 8219,16411,16412, 8219,16411,16412, 8219,16411,
    16412, 8219,16411,16412, 8219,16411,16412, 8219,16411,16412,
     8219,16411,16412,   54,   35,   34,   35,   34,   33,   32,
       35,   30,   35,   31,   35,    2,    4,   40,   38,   40,
       38,   40,   38, 8219, 8220,   22, 8219,16411,16412, 8219,
    16411,16412, 8219,16411,16412, 8219,16411,16412, 8219,16411,
    16412, 8219,16411,16412, 8219,16411,16412, 8219,16411,16412,
     8219,16411,16412, 8219,16411,16412,   16, 8219,16411,16412,

     8219,16411,16412,    6, 8219,16411,16412, 8219,16411,16412,
     8219,16411,16412, 8219,16411,16412, 8219,16411,16412, 8219,
    16411,16412, 8219,16411,16412, 8219,16411,16412, 8219,16411,
    16412, 8219,16411,16412, 8219,16411,16412,    8, 8219,16411,
    16412, 8219,16411,16412, 8219,16411,16412, 8219,16411,16412,
       19, 8219,16411,16412, 8219,16411,16412, 8219,16411,16412,
       18, 8219, 8220, 8219,16411,16412, 8219,16411,16412,   12,
     8219,16411,16412, 8219,16411,16412, 8219,16411,16412,   13,
     8219,16411,16412, 8219,   39,16411,16412,    5, 8219,16411,
    16412, 8219,16411,16412,   22, 8219, 8220, 8219,16411,16412,

       24, 8219,16411,16412, 8219,16411,16412, 8219,16411,16412,
       21, 8219,16411,16412,   10, 8219,16411,16412, 8219,16411,
    16412, 8219,16411,16412,   16, 8219, 8220, 8219,16411,16412,
        6, 8219, 8220, 8219,16411,16412, 8219,16411,16412, 8219,
    16411,16412,   17, 8219,16411,16412, 8219,16411,16412, 8219,
    16411,16412, 8219,16411,16412,    8, 8219, 8220,    7, 8219,
    16411,16412,   19, 8219, 8220, 8219,16411,16412, 8219,16411,
    16412, 8219,16411,16412,   12, 8219, 8220,   20, 8219,16411,
    16412,    9, 8219,16411,16412,   13, 8219, 8220,    5, 8219,
     8220, 8219,16411,16412,   24, 8219, 8220, 8219,16411,16412,

     8219,16411,16412,   21, 8219, 8220,   10, 8219, 8220,   14,
     8219,16411,16412, 8219,16411,16412, 8219,16411,16412,   17,
     8219, 8220,   23, 8219,16411,16412, 8219,16411,16412,   26,
     8219,16411,16412,    7, 8219, 8220, 8219,16411,16412, 8219,
    16411,16412,   20, 8219, 8220,    9, 8219, 8220, 8219,16411,
    16412,   14, 8219, 8220, 8219,16411,16412,   11, 8219,16411,
    16412,   23, 8219, 8220, 8219,16411,16412,   26, 8219, 8220,
       15, 8219,16411,16412,   25, 8219,16411,16412,   11, 8219,
     8220,   15, 8219, 8220,   25, 8219, 8220
    } ;

static yyconst flex_int16_t yy_accept[275] =
    {   0,
        1,    1,    1,    2,    3,    3,    3,    4,    6,    9,
       11,   14,   17,   20,   22,   25,   28,   31,   34,   37,
       40,   43,   46,   49,   52,   55,   58,   61,   64,   69,
       74,   79,   84,   87,   90,   95,  100,  105,  110,  115,
      120,  125,  130,  135,  140,  145,  150,  153,  155,  158,
      160,  162,  164,  166,  168,  170,  171,  172,  173,  173,
      173,  174,  174,  175,  176,  177,  177,  180,  180,  183,
      186,  189,  192,  195,  198,  201,  204,  207,  210,  213,
      217,  220,  223,  226,  229,  232,  235,  238,  241,  244,
      245,  246,  248,  249,  250,  252,  254,  256,  257,  257,

      258,  259,  261,  263,  264,  266,  266,  270,  273,  276,
      279,  282,  285,  288,  291,  294,  297,  301,  301,  301,
      304,  308,  311,  314,  317,  320,  323,  326,  329,  329,
      332,  332,  335,  338,  342,  345,  348,  351,  355,  358,
      361,  361,  361,  364,  364,  367,  367,  367,  370,  374,
      377,  380,  384,  388,  392,  395,  398,  401,  401,  405,
      408,  411,  411,  411,  415,  419,  422,  422,  422,  425,
      428,  428,  431,  434,  434,  437,  437,  437,  440,  443,
      443,  443,  443,  443,  447,  450,  450,  450,  453,  456,
      459,  459,  459,  459,  459,  459,  463,  466,  466,  469,

      472,  475,  478,  478,  482,  486,  489,  489,  492,  492,
      492,  492,  495,  498,  498,  501,  504,  507,  507,  510,
      510,  510,  510,  514,  517,  520,  520,  520,  520,  520,
      523,  523,  527,  530,  534,  537,  537,  537,  537,  540,
      543,  546,  546,  549,  549,  549,  549,  552,  552,  552,
      555,  555,  558,  562,  565,  565,  568,  571,  571,  575,
      575,  575,  579,  579,  579,  582,  582,  582,  582,  585,
      585,  588,  588,  588
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    1,    1,    6,    7,    1,    8,
        9,   10,   11,   12,   13,   14,   15,   16,   17,   17,
       17,   17,   17,   17,   17,   17,   17,    1,   18,   19,
       20,   21,    1,    1,   22,   23,   23,   23,   23,   23,
       24,   24,   25,   24,   24,   26,   24,   27,   24,   28,
       24,   29,   24,   24,   24,   24,   24,   30,   24,   24,
       31,   32,   33,    1,   34,    1,   35,   36,   37,   38,

       39,   40,   41,   42,   43,   24,   44,   45,   46,   47,
       48,   49,   24,   50,   51,   52,   53,   54,   55,   56,
       57,   24,   58,   59,   60,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[61] =
    {   0,
        1,    2,    3,    1,    4,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    5,    5,    1,    1,    1,
        1,    6,    6,    2,    2,    2,    2,    2,    2,    2,
        2,    1,    1,    7,    6,    6,    6,    6,    6,    6,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    1,    1,    1
    } ;

static yyconst flex_int16_t yy_base[305] =
    {   0,
        0,    0,   58,   59,  112,  110,  117, 1095, 1095, 1095,
       94, 1095, 1095,  105, 1095, 1095, 1095, 1095, 1095, 1095,
     1095,   55,   50,   52, 1095,   85,   83,   81,   69,   71,
       73,   76, 1095, 1095,   80,   82,   85,   90,   94,  116,
      106,  129,  136,  141,  138,  147, 1095,   30, 1095,    0,
     1095, 1095,  148, 1095,   71, 1095, 1095, 1095,   78,   78,
       82,  138, 1095, 1095, 1095,  163,  168,  171,  174,  177,
      179,  182,  194,  200,  190,  209,  213,  216,  220,  224,
      235,  243,  246,  250,  254,  256,  261,  265,  269, 1095,
        0,    0, 1095, 1095,    0,    0,    0, 1095,   74, 1095,

      141,  190,  225,    0, 1095,  273,  276,  280,  286,  291,
      307,  313,  316,  318,  323,  327,  329,  332,  337,  343,
      348,  353,  363,  365,  369,  373,  379,  383,  387,  390,
      399,  403,  420,  422,  427,  433,  435,  439,  441,  446,
      458,  424, 1095,  460,  465,  471,  473,  476,  479,  484,
      488,  492,  496,  498,  506, 1095,  509,  511,  515,  518,
      529,  522,  536,  539,  545,  548,  552,  555,  559, 1095,
      561,  564, 1095,  571,  575,  578,  583,  589,  596,  598,
      600,  609,  605,  611,  615,  620,  622,  628,  632, 1095,
      641,  645,  650,  654,  658,  662, 1095,  664,  667,  669,

      675, 1095,  679,  684,  686, 1095,  692, 1095,  699,  702,
      711,  717, 1095,  719,  724,  726, 1095,  721, 1095,  728,
      733,  735,  738,  740,  744,  747,  756,  764,  770, 1095,
      774,  777,  780,  782, 1095,  789,  794,  791,  796,  798,
     1095,  802, 1095,  807,  812,  814,  828,  830,  816, 1095,
      836,  839,  842, 1095,  848,  851, 1095,  853,  860,  862,
      855,  869,  872,  874, 1095,  876,  881,  892, 1095,  894,
     1095,  896, 1095,  929,  936,  943,  949,  956,  963,  970,
      973,  978,  983,  988,  993,  998, 1003, 1008, 1013, 1018,
     1023, 1028, 1033, 1038, 1043, 1048, 1053, 1058, 1063, 1068,

     1073, 1078, 1083, 1088
    } ;

static yyconst flex_int16_t yy_def[305] =
    {   0,
      273,    1,  274,  274,  275,  275,  273,  273,  273,  273,
      273,  273,  273,  273,  273,  273,  273,  273,  273,  273,
      273,  273,  276,  276,  273,  273,  273,  273,  277,  277,
      277,  277,  273,  273,  277,  277,  277,  277,  277,  277,
      277,  277,  277,  277,  277,  277,  273,  273,  273,  278,
      273,  273,  279,  273,  273,  273,  273,  273,  280,  273,
      276,  281,  273,  273,  273,  282,  277,  273,  277,  277,
      277,  277,  277,  277,  277,  277,  277,  277,  277,  277,
      277,  277,  277,  277,  277,  277,  277,  277,  277,  273,
      278,  278,  273,  273,  278,  278,  278,  273,  280,  273,

      273,  276,  281,  281,  273,  273,  277,  277,  277,  277,
      277,  277,  277,  277,  277,  277,  277,  283,  273,  277,
      277,  277,  277,  277,  277,  277,  277,  277,  284,  277,
      273,  277,  277,  277,  277,  277,  277,  277,  277,  277,
      285,  273,  273,  273,  277,  286,  273,  277,  277,  277,
      277,  277,  277,  277,  277,  273,  277,  273,  277,  277,
      277,  287,  273,  277,  277,  277,  288,  273,  277,  273,
      273,  277,  273,  273,  277,  289,  273,  277,  277,  290,
      273,  291,  273,  277,  277,  292,  273,  277,  277,  273,
      273,  293,  273,  294,  273,  277,  273,  273,  277,  277,

      277,  273,  273,  277,  277,  273,  273,  273,  273,  295,
      273,  277,  273,  273,  277,  277,  273,  273,  273,  273,
      296,  273,  277,  277,  277,  297,  273,  298,  273,  273,
      273,  277,  277,  277,  273,  273,  299,  273,  277,  277,
      273,  273,  273,  273,  300,  273,  277,  301,  273,  273,
      273,  277,  277,  273,  273,  277,  273,  273,  277,  302,
      273,  277,  303,  273,  273,  273,  304,  273,  273,  273,
      273,  273,    0,  273,  273,  273,  273,  273,  273,  273,
      273,  273,  273,  273,  273,  273,  273,  273,  273,  273,
      273,  273,  273,  273,  273,  273,  273,  273,  273,  273,

      273,  273,  273,  273
    } ;

static yyconst flex_int16_t yy_nxt[1156] =
    {   0,
        8,    9,   10,   11,   12,   13,   14,   15,   16,   17,
       18,   19,   20,   21,   22,   23,   24,   25,   26,   27,
       28,   29,   29,   29,   29,   29,   30,   31,   32,   29,
       33,    8,   34,    8,   29,   35,   36,   37,   38,   39,
       29,   29,   40,   29,   29,   29,   41,   29,   29,   42,
       43,   44,   29,   45,   46,   29,   29,   47,   48,   49,
       51,   51,   52,   52,   58,   61,   61,   61,   61,   59,
       66,   66,   66,   66,   66,   66,  100,   66,   66,   62,
      100,   66,   66,   66,   66,   98,   66,   66,   90,   53,
       53,   66,   66,  101,  101,   66,   66,  102,  102,   68,

       65,   68,   64,   68,   63,   62,   68,   66,   66,   69,
       68,   57,   68,   56,   71,   68,  273,   66,   66,   55,
       68,   55,   70,  273,   68,  273,   74,   72,   78,   73,
       66,   66,   75,  273,   76,  273,   68,   66,   66,   66,
       66,   79,   66,   66,  273,   77,   68,  273,   66,   66,
       93,  273,   94,  103,  103,   80,  101,  101,   83,   68,
      273,   81,   82,   95,   66,   66,   68,   84,   68,   66,
       66,   68,  106,  106,  273,   66,   66,   68,   66,   66,
       66,   66,   86,   66,   66,   88,  273,   85,   89,  273,
       87,   66,   66,   68,   96,   66,   66,  273,   68,   97,

      273,   66,   66,  105,   68,  102,  102,   68,  273,   68,
       66,   66,   68,  109,   66,   66,  273,   66,   66,  108,
       68,   66,   66,  273,   68,  118,  118,  273,  107,  110,
       68,  273,  111,  273,  112,  273,   66,   66,  273,   68,
      103,  103,  113,   68,   66,   66,   68,   66,   66,  273,
       68,   66,   66,  273,  119,   66,   66,   66,   66,  114,
      116,  273,   66,   66,  115,   68,   66,   66,  273,  117,
       66,   66,  273,   68,  106,  106,   68,  129,  129,  273,
       68,   66,   66,  120,   68,  273,   68,   66,   66,  273,
      122,   68,   66,   66,  121,   68,  273,  130,  125,   68,

      273,  123,  273,  124,  273,  105,  131,  127,   66,   66,
       68,  128,  273,  126,   66,   66,   68,   66,   66,   66,
       66,   68,  273,  133,   66,   66,  132,  273,   66,   66,
      141,  141,  273,  118,  118,  134,  273,   68,  144,  144,
      273,  135,  273,   68,   66,   66,   68,  273,   68,  146,
      146,  137,  273,   68,   66,   66,  138,   68,  273,  142,
      273,  139,  119,  136,   66,   66,   66,   66,  273,  143,
       66,   66,  273,   68,   66,   66,  273,  140,  147,  273,
       66,   66,  273,   68,   66,   66,  148,  145,  129,  129,
      273,   66,   66,   68,  273,   68,  273,  149,  273,   68,

      158,  158,  273,   68,   66,   66,  273,  151,  273,   68,
      273,  153,  273,   68,  273,  150,  154,  131,  273,  152,
       68,   66,   66,  162,  162,  171,  171,  155,   66,   66,
      273,  156,  273,   68,   66,   66,   66,   66,  273,  157,
      167,  167,   66,   66,  160,  161,  273,   66,   66,  273,
       68,  273,  163,  273,  159,  273,  170,   68,  273,  141,
      141,  144,  144,   68,  273,   68,   66,   66,  273,  168,
      164,   68,  146,  146,  174,  174,   68,   66,   66,  166,
      176,  176,  273,  165,  153,   66,   66,  169,  142,   66,
       66,  273,  143,  180,  180,   68,  273,   66,   66,  182,

      182,  147,  273,  172,  273,  173,   68,   66,   66,  177,
       66,   66,  158,  158,   68,  273,  186,  186,   68,   66,
       66,  273,  181,  162,  162,  175,   68,  273,  183,  273,
       66,   66,  273,  178,  179,  273,   68,  191,  191,   68,
      192,  192,  273,  156,  184,  187,  194,  194,   68,   66,
       66,  273,  163,  167,  167,  273,  198,  198,  185,   68,
       66,   66,  171,  171,  188,   66,   66,  273,  190,  193,
      273,  189,  174,  174,  273,  195,   66,   66,   68,  176,
      176,  273,  168,  273,  203,  203,  196,  197,  273,   68,
       66,   66,  273,  170,   68,  273,  199,   66,   66,  180,

      180,  207,  207,  173,  273,   68,  209,  209,  177,  200,
      182,  182,  210,  210,  201,  202,   66,   66,  273,   68,
      273,  186,  186,  214,  214,  273,   68,  273,  181,   66,
       66,  273,  206,   66,   66,  204,  205,  208,  273,  183,
      273,  211,  191,  191,  273,   68,  192,  192,  273,  212,
      187,  218,  218,  273,  213,  194,  194,  273,   68,  220,
      220,  273,   68,  221,  221,  198,  198,  273,   66,   66,
       66,   66,  273,  190,  273,  193,   66,   66,  216,  215,
      203,  203,  217,  273,  195,  226,  226,  228,  228,  273,
      219,  273,  222,  207,  207,  273,  197,   68,  273,   68,

      209,  209,  273,  210,  210,   68,  273,  224,  273,  225,
      273,  202,  231,  231,  227,  273,  229,  223,   66,   66,
      214,  214,  218,  218,  206,   66,   66,   66,   66,  220,
      220,  208,  211,  273,  221,  221,  236,  236,  273,  237,
      237,   66,   66,  230,  273,   66,   66,   68,  226,  226,
      273,  213,  273,  217,   68,  273,   68,  242,  242,  273,
      219,  273,  233,  222,  234,  228,  228,  235,  238,  273,
       68,  244,  244,  232,   68,  231,  231,  227,  245,  245,
      240,   66,   66,  248,  248,  273,  239,  273,  241,  273,
      236,  236,  251,  251,  229,  237,  237,   66,   66,   66,

       66,  273,  243,  242,  242,  273,  230,  246,  244,  244,
       68,  273,  249,  245,  245,  255,  255,  258,  258,  273,
      247,  235,  273,  250,  238,  273,   68,  273,   68,   66,
       66,  248,  248,  273,  241,  273,  253,  251,  251,  243,
       66,   66,  246,  260,  260,  273,  254,  252,  257,  255,
      255,  273,   66,   66,  258,  258,  266,  266,   68,  273,
      249,  263,  263,  260,  260,  273,  256,  273,  250,   68,
      267,  267,  261,  263,  263,  270,  270,  266,  266,  273,
      254,   68,  267,  267,  273,  257,  273,  265,  273,  259,
      264,  273,  261,  272,  272,  270,  270,  272,  272,  268,

      262,  273,  264,  273,  273,  273,  269,  273,  265,  273,
      273,  268,  273,  273,  273,  273,  273,  273,  273,  273,
      273,  273,  273,  273,  271,  273,  269,  273,  271,   50,
       50,   50,   50,   50,   50,   50,   54,   54,   54,   54,
       54,   54,   54,   60,   60,  273,   60,   60,   60,   60,
       67,   67,  273,   67,   67,   67,   91,   91,  273,  273,
       91,   91,   91,   92,   92,   92,   92,   92,   92,   92,
       99,   99,   99,   99,   99,   99,   99,  104,  104,  105,
      105,  273,  273,  105,  143,  143,  273,  273,  143,  156,
      156,  273,  273,  156,  170,  170,  273,  273,  170,  173,

      173,  273,  273,  173,  190,  190,  273,  273,  190,  197,
      197,  273,  273,  197,  202,  202,  273,  273,  202,  206,
      206,  273,  273,  206,  208,  208,  273,  273,  208,  213,
      213,  273,  273,  213,  217,  217,  273,  273,  217,  219,
      219,  273,  273,  219,  230,  230,  273,  273,  230,  235,
      235,  273,  273,  235,  241,  241,  273,  273,  241,  243,
      243,  273,  273,  243,  250,  250,  273,  273,  250,  254,
      254,  273,  273,  254,  257,  257,  273,  273,  257,  265,
      265,  273,  273,  265,  269,  269,  273,  273,  269,  271,
      271,  273,  273,  271,    7,  273,  273,  273,  273,  273,

      273,  273,  273,  273,  273,  273,  273,  273,  273,  273,
      273,  273,  273,  273,  273,  273,  273,  273,  273,  273,
      273,  273,  273,  273,  273,  273,  273,  273,  273,  273,
      273,  273,  273,  273,  273,  273,  273,  273,  273,  273,
      273,  273,  273,  273,  273,  273,  273,  273,  273,  273,
      273,  273,  273,  273,  273
    } ;

static yyconst flex_int16_t yy_chk[1156] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        3,    4,    3,    4,   22,   23,   23,   24,   24,   22,
       29,   29,   30,   30,   31,   31,   99,   32,   32,   23,
       59,   35,   35,   36,   36,   55,   37,   37,   48,    3,
        4,   38,   38,   60,   60,   39,   39,   61,   61,   29,

       28,   30,   27,   31,   26,   23,   32,   41,   41,   30,
       35,   14,   36,   11,   32,   37,    7,   40,   40,    6,
       38,    5,   31,    0,   39,    0,   36,   35,   39,   35,
       42,   42,   37,    0,   38,    0,   41,   43,   43,   45,
       45,   39,   44,   44,    0,   38,   40,    0,   46,   46,
       53,    0,   53,   62,   62,   40,  101,  101,   41,   42,
        0,   40,   40,   53,   66,   66,   43,   42,   45,   67,
       67,   44,   68,   68,    0,   69,   69,   46,   70,   70,
       71,   71,   44,   72,   72,   45,    0,   43,   46,    0,
       44,   75,   75,   66,   53,   73,   73,    0,   67,   53,

        0,   74,   74,   68,   69,  102,  102,   70,    0,   71,
       76,   76,   72,   71,   77,   77,    0,   78,   78,   70,
       75,   79,   79,    0,   73,   80,   80,    0,   69,   72,
       74,    0,   73,    0,   74,    0,   81,   81,    0,   76,
      103,  103,   75,   77,   82,   82,   78,   83,   83,    0,
       79,   84,   84,    0,   80,   85,   85,   86,   86,   76,
       78,    0,   87,   87,   77,   81,   88,   88,    0,   79,
       89,   89,    0,   82,  106,  106,   83,  107,  107,    0,
       84,  108,  108,   81,   85,    0,   86,  109,  109,    0,
       83,   87,  110,  110,   82,   88,    0,  107,   86,   89,

        0,   84,    0,   85,    0,  106,  107,   88,  111,  111,
      108,   89,    0,   87,  112,  112,  109,  113,  113,  114,
      114,  110,    0,  109,  115,  115,  108,    0,  116,  116,
      117,  117,    0,  118,  118,  110,    0,  111,  119,  119,
        0,  111,    0,  112,  120,  120,  113,    0,  114,  121,
      121,  113,    0,  115,  122,  122,  114,  116,    0,  117,
        0,  115,  118,  112,  123,  123,  124,  124,    0,  119,
      125,  125,    0,  120,  126,  126,    0,  116,  121,    0,
      127,  127,    0,  122,  128,  128,  121,  120,  129,  129,
        0,  130,  130,  123,    0,  124,    0,  122,    0,  125,

      131,  131,    0,  126,  132,  132,    0,  124,    0,  127,
        0,  126,    0,  128,    0,  123,  127,  129,    0,  125,
      130,  133,  133,  134,  134,  142,  142,  128,  135,  135,
        0,  131,    0,  132,  136,  136,  137,  137,    0,  130,
      138,  138,  139,  139,  133,  133,    0,  140,  140,    0,
      133,    0,  134,    0,  132,    0,  142,  135,    0,  141,
      141,  144,  144,  136,    0,  137,  145,  145,    0,  138,
      135,  139,  146,  146,  147,  147,  140,  148,  148,  137,
      149,  149,    0,  136,  140,  150,  150,  139,  141,  151,
      151,    0,  144,  152,  152,  145,    0,  153,  153,  154,

      154,  146,    0,  145,    0,  147,  148,  155,  155,  149,
      157,  157,  158,  158,  150,    0,  159,  159,  151,  160,
      160,    0,  152,  162,  162,  148,  153,    0,  154,    0,
      161,  161,    0,  150,  151,    0,  155,  163,  163,  157,
      164,  164,    0,  158,  155,  159,  165,  165,  160,  166,
      166,    0,  162,  167,  167,    0,  168,  168,  157,  161,
      169,  169,  171,  171,  160,  172,  172,    0,  163,  164,
        0,  161,  174,  174,    0,  165,  175,  175,  166,  176,
      176,    0,  167,    0,  177,  177,  166,  168,    0,  169,
      178,  178,    0,  171,  172,    0,  169,  179,  179,  180,

      180,  181,  181,  174,    0,  175,  183,  183,  176,  172,
      182,  182,  184,  184,  175,  177,  185,  185,    0,  178,
        0,  186,  186,  187,  187,    0,  179,    0,  180,  188,
      188,    0,  181,  189,  189,  178,  179,  183,    0,  182,
        0,  184,  191,  191,    0,  185,  192,  192,    0,  185,
      186,  193,  193,    0,  187,  194,  194,    0,  188,  195,
      195,    0,  189,  196,  196,  198,  198,    0,  199,  199,
      200,  200,    0,  191,    0,  192,  201,  201,  189,  188,
      203,  203,  193,    0,  194,  204,  204,  205,  205,    0,
      195,    0,  196,  207,  207,    0,  198,  199,    0,  200,

      209,  209,    0,  210,  210,  201,    0,  200,    0,  201,
        0,  203,  211,  211,  204,    0,  205,  199,  212,  212,
      214,  214,  218,  218,  207,  215,  215,  216,  216,  220,
      220,  209,  210,    0,  221,  221,  222,  222,    0,  223,
      223,  224,  224,  211,    0,  225,  225,  212,  226,  226,
        0,  214,    0,  218,  215,    0,  216,  227,  227,    0,
      220,    0,  215,  221,  216,  228,  228,  222,  223,    0,
      224,  229,  229,  212,  225,  231,  231,  226,  232,  232,
      225,  233,  233,  234,  234,    0,  224,    0,  227,    0,
      236,  236,  238,  238,  228,  237,  237,  239,  239,  240,

      240,    0,  229,  242,  242,    0,  231,  232,  244,  244,
      233,    0,  234,  245,  245,  246,  246,  249,  249,    0,
      233,  236,    0,  238,  237,    0,  239,    0,  240,  247,
      247,  248,  248,    0,  242,    0,  240,  251,  251,  244,
      252,  252,  245,  253,  253,    0,  246,  239,  249,  255,
      255,    0,  256,  256,  258,  258,  261,  261,  247,    0,
      248,  259,  259,  260,  260,    0,  247,    0,  251,  252,
      262,  262,  253,  263,  263,  264,  264,  266,  266,    0,
      255,  256,  267,  267,    0,  258,    0,  261,    0,  252,
      259,    0,  260,  268,  268,  270,  270,  272,  272,  262,

      256,    0,  263,    0,    0,    0,  264,    0,  266,    0,
        0,  267,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,  268,    0,  270,    0,  272,  274,
      274,  274,  274,  274,  274,  274,  275,  275,  275,  275,
      275,  275,  275,  276,  276,    0,  276,  276,  276,  276,
      277,  277,    0,  277,  277,  277,  278,  278,    0,    0,
      278,  278,  278,  279,  279,  279,  279,  279,  279,  279,
      280,  280,  280,  280,  280,  280,  280,  281,  281,  282,
      282,    0,    0,  282,  283,  283,    0,    0,  283,  284,
      284,    0,    0,  284,  285,  285,    0,    0,  285,  286,

      286,    0,    0,  286,  287,  287,    0,    0,  287,  288,
      288,    0,    0,  288,  289,  289,    0,    0,  289,  290,
      290,    0,    0,  290,  291,  291,    0,    0,  291,  292,
      292,    0,    0,  292,  293,  293,    0,    0,  293,  294,
      294,    0,    0,  294,  295,  295,    0,    0,  295,  296,
      296,    0,    0,  296,  297,  297,    0,    0,  297,  298,
      298,    0,    0,  298,  299,  299,    0,    0,  299,  300,
      300,    0,    0,  300,  301,  301,    0,    0,  301,  302,
      302,    0,    0,  302,  303,  303,    0,    0,  303,  304,
      304,    0,    0,  304,  273,  273,  273,  273,  273,  273,

      273,  273,  273,  273,  273,  273,  273,  273,  273,  273,
      273,  273,  273,  273,  273,  273,  273,  273,  273,  273,
      273,  273,  273,  273,  273,  273,  273,  273,  273,  273,
      273,  273,  273,  273,  273,  273,  273,  273,  273,  273,
      273,  273,  273,  273,  273,  273,  273,  273,  273,  273,
      273,  273,  273,  273,  273
    } ;

/* Table of booleans, true if rule could match eol. */
static yyconst flex_int32_t yy_rule_can_match_eol[68] =
    {   0,
0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 
    1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 1, 0, 0,     };

extern int yy_flex_debug;
int yy_flex_debug = 0;

static yy_state_type *yy_state_buf=0, *yy_state_ptr=0;
static char *yy_full_match;
static int yy_lp;
static int yy_looking_for_trail_begin = 0;
static int yy_full_lp;
static int *yy_full_state;
#define YY_TRAILING_MASK 0x2000
#define YY_TRAILING_HEAD_MASK 0x4000
#define REJECT \
{ \
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */ \
yy_cp = (yy_full_match); /* restore poss. backed-over text */ \
(yy_lp) = (yy_full_lp); /* restore orig. accepting pos. */ \
(yy_state_ptr) = (yy_full_state); /* restore orig. state */ \
yy_current_state = *(yy_state_ptr); /* restore curr. state */ \
++(yy_lp); \
goto find_rule; \
}

#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "decaf.lex"
/* definitions */
#line 4 "decaf.lex"

#include <iostream>

using namespace std;

#include "tokentype.h"

string resultString;
int startline;
Token* myTok;

int error(string msg, int line)
{
  cout << msg << " on line " << line << endl;
  return -1;
}

TokenType makeToken(TokenType type) {
    myTok = new Token(type, yytext, yylineno);
    return type;
}

int ident_error(char * txt, int line) {
  cout << "identifier" << txt << "too long on line" << line << endl;
  return -1;
}




#line 935 "lex.yy.c"

#define INITIAL 0
#define STRING 1
#define BCOMM 2

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 40 "decaf.lex"


  /* rules */

  /* block comment machine */
#line 1125 "lex.yy.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

        /* Create the reject buffer large enough to save one state per allowed character. */
        if ( ! (yy_state_buf) )
            (yy_state_buf) = (yy_state_type *)yyalloc(YY_STATE_BUF_SIZE  );
            if ( ! (yy_state_buf) )
                YY_FATAL_ERROR( "out of dynamic memory in yylex()" );

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);

		(yy_state_ptr) = (yy_state_buf);
		*(yy_state_ptr)++ = yy_current_state;

yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 274 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*(yy_state_ptr)++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1095 );

yy_find_action:
		yy_current_state = *--(yy_state_ptr);
		(yy_lp) = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( (yy_lp) && (yy_lp) < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[(yy_lp)];
				if ( yy_act & YY_TRAILING_HEAD_MASK ||
				     (yy_looking_for_trail_begin) )
					{
					if ( yy_act == (yy_looking_for_trail_begin) )
						{
						(yy_looking_for_trail_begin) = 0;
						yy_act &= ~YY_TRAILING_HEAD_MASK;
						break;
						}
					}
				else if ( yy_act & YY_TRAILING_MASK )
					{
					(yy_looking_for_trail_begin) = yy_act & ~YY_TRAILING_MASK;
					(yy_looking_for_trail_begin) |= YY_TRAILING_HEAD_MASK;
					}
				else
					{
					(yy_full_match) = yy_cp;
					(yy_full_state) = (yy_state_ptr);
					(yy_full_lp) = (yy_lp);
					break;
					}
				++(yy_lp);
				goto find_rule;
				}
			--yy_cp;
			yy_current_state = *--(yy_state_ptr);
			(yy_lp) = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			yy_size_t yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					   
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
YY_RULE_SETUP
#line 45 "decaf.lex"
{ BEGIN(BCOMM); startline = yylineno; }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 46 "decaf.lex"
{ BEGIN(INITIAL); }
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 47 "decaf.lex"
{}
	YY_BREAK
case YY_STATE_EOF(BCOMM):
#line 48 "decaf.lex"
{ return error("Missing */ for block comment starting", startline); }
	YY_BREAK
/* Single line comment */
case 4:
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 51 "decaf.lex"
{}
	YY_BREAK
/* keywords */
case 5:
/* rule 5 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp = yy_bp + 4;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 56 "decaf.lex"
{ return makeToken(T_Void); }
	YY_BREAK
case 6:
/* rule 6 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp = yy_bp + 3;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 57 "decaf.lex"
{ return makeToken(T_Int); }
	YY_BREAK
case 7:
/* rule 7 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp = yy_bp + 6;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 58 "decaf.lex"
{ return makeToken(T_Double); }
	YY_BREAK
case 8:
/* rule 8 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp = yy_bp + 4;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 59 "decaf.lex"
{ return makeToken(T_Bool); }
	YY_BREAK
case 9:
/* rule 9 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp = yy_bp + 6;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 60 "decaf.lex"
{ return makeToken(T_String); }
	YY_BREAK
case 10:
/* rule 10 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp = yy_bp + 5;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 61 "decaf.lex"
{ return makeToken(T_Class); }
	YY_BREAK
case 11:
/* rule 11 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp = yy_bp + 9;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 62 "decaf.lex"
{ return makeToken(T_Interface); }
	YY_BREAK
case 12:
/* rule 12 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp = yy_bp + 4;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 63 "decaf.lex"
{ return makeToken(T_Null); }
	YY_BREAK
case 13:
/* rule 13 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp = yy_bp + 4;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 64 "decaf.lex"
{ return makeToken(T_This); }
	YY_BREAK
case 14:
/* rule 14 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp = yy_bp + 7;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 65 "decaf.lex"
{ return makeToken(T_Extends); }
	YY_BREAK
case 15:
/* rule 15 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp = yy_bp + 10;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 66 "decaf.lex"
{ return makeToken(T_Implements); }
	YY_BREAK
case 16:
/* rule 16 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp = yy_bp + 3;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 67 "decaf.lex"
{ return makeToken(T_For); }
	YY_BREAK
case 17:
/* rule 17 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp = yy_bp + 5;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 68 "decaf.lex"
{ return makeToken(T_While); }
	YY_BREAK
case 18:
/* rule 18 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp = yy_bp + 2;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 69 "decaf.lex"
{ return makeToken(T_If); }
	YY_BREAK
case 19:
/* rule 19 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp = yy_bp + 4;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 70 "decaf.lex"
{ return makeToken(T_Else); }
	YY_BREAK
case 20:
/* rule 20 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp = yy_bp + 6;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 71 "decaf.lex"
{ return makeToken(T_Return); }
	YY_BREAK
case 21:
/* rule 21 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp = yy_bp + 5;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 72 "decaf.lex"
{ return makeToken(T_Break); }
	YY_BREAK
case 22:
/* rule 22 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp = yy_bp + 3;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 73 "decaf.lex"
{ return makeToken(T_New); }
	YY_BREAK
case 23:
/* rule 23 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp = yy_bp + 8;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 74 "decaf.lex"
{ return makeToken(T_NewArray); }
	YY_BREAK
case 24:
/* rule 24 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp = yy_bp + 5;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 75 "decaf.lex"
{ return makeToken(T_Print); }
	YY_BREAK
case 25:
/* rule 25 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp = yy_bp + 11;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 76 "decaf.lex"
{ return makeToken(T_ReadInteger); }
	YY_BREAK
case 26:
/* rule 26 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp = yy_bp + 8;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 77 "decaf.lex"
{ return makeToken(T_ReadLine); }
	YY_BREAK
/* identifier */
case 27:
/* rule 27 can match eol */
YY_RULE_SETUP
#line 81 "decaf.lex"
{ if (yyleng > 31) return ident_error(yytext, yylineno); return makeToken(T_Identifier); }
	YY_BREAK
/* type ident */
case 28:
/* rule 28 can match eol */
YY_RULE_SETUP
#line 85 "decaf.lex"
{ return makeToken(T_TypeIdentifier); }
	YY_BREAK
/* string literal */
/* \"(.|\\.)*\"  { return makeToken(T_StringConstant); }  */
/* \"([^\"][\\.])*\"$ { return makeToken(T_StringConstant); } */
case 29:
YY_RULE_SETUP
#line 91 "decaf.lex"
{ BEGIN(STRING); resultString = "\""; cout << "Revving up the string machine my dudes!!" << endl; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 92 "decaf.lex"
{ resultString += '\n'; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 93 "decaf.lex"
{ resultString += '\t'; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 94 "decaf.lex"
{ resultString += '\0'; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 95 "decaf.lex"
{ resultString += '"'; }
	YY_BREAK
case 34:
/* rule 34 can match eol */
YY_RULE_SETUP
#line 96 "decaf.lex"
{ }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 97 "decaf.lex"
{ resultString += yytext; }
	YY_BREAK
case 36:
/* rule 36 can match eol */
YY_RULE_SETUP
#line 98 "decaf.lex"
{return error("missing \" at end of string constant", 
		yylineno-1); }
	YY_BREAK
case YY_STATE_EOF(STRING):
#line 100 "decaf.lex"
{return error("missing \" at end of string constant", 
		yylineno); } 
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 102 "decaf.lex"
{ BEGIN(INITIAL); 
	         myTok = new Token(T_StringConstant,resultString + "\"", 
                                  yylineno);
		 return T_StringConstant; }
	YY_BREAK
/* Int constant */
case 38:
YY_RULE_SETUP
#line 108 "decaf.lex"
{ return makeToken(T_IntConstant); }
	YY_BREAK
/* Boolean constant */
case 39:
YY_RULE_SETUP
#line 111 "decaf.lex"
{return makeToken(T_BoolConstant); }
	YY_BREAK
/* Double Constant */
case 40:
YY_RULE_SETUP
#line 114 "decaf.lex"
{ return makeToken(T_DoubleConstant); }
	YY_BREAK
/* Operator tokens */
case 41:
YY_RULE_SETUP
#line 117 "decaf.lex"
{ return makeToken(T_Plus); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 118 "decaf.lex"
{ return makeToken(T_Minus); } 
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 119 "decaf.lex"
{ return makeToken(T_Times); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 120 "decaf.lex"
{ return makeToken(T_Div); }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 121 "decaf.lex"
{ return makeToken(T_Mod); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 122 "decaf.lex"
{ return makeToken(T_Less); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 123 "decaf.lex"
{ return makeToken(T_LessEqual); }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 124 "decaf.lex"
{ return makeToken(T_Greater); }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 125 "decaf.lex"
{ return makeToken(T_GreaterEqual); }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 126 "decaf.lex"
{ return makeToken(T_Assign); }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 127 "decaf.lex"
{ return makeToken(T_Equal); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 128 "decaf.lex"
{ return makeToken(T_NotEqual); }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 129 "decaf.lex"
{ return makeToken(T_And); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 130 "decaf.lex"
{ return makeToken(T_Or); }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 131 "decaf.lex"
{ return makeToken(T_Not); }
	YY_BREAK
/* Other tokens */
case 56:
YY_RULE_SETUP
#line 134 "decaf.lex"
{ return makeToken(T_Semicolon); }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 135 "decaf.lex"
{ return makeToken(T_Comma); }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 136 "decaf.lex"
{ return makeToken(T_Dot); }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 137 "decaf.lex"
{ return makeToken(T_LBracket); }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 138 "decaf.lex"
{ return makeToken(T_RBracket); }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 139 "decaf.lex"
{ return makeToken(T_LParen); }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 140 "decaf.lex"
{ return makeToken(T_RParen); }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 141 "decaf.lex"
{ return makeToken(T_LBrace); }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 142 "decaf.lex"
{ return makeToken(T_RBrace); }
	YY_BREAK
/* Ignore whitespace */
case 65:
/* rule 65 can match eol */
YY_RULE_SETUP
#line 145 "decaf.lex"
{}
	YY_BREAK
/* DELETE THIS EVENTUALLY OR THROW ERROR STRAY CHAR */
case 66:
YY_RULE_SETUP
#line 148 "decaf.lex"
{ std::string s = "Stray "; return error(s + yytext, yylineno); }
	YY_BREAK
case YY_STATE_EOF(INITIAL):
#line 152 "decaf.lex"
{ return -1; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 154 "decaf.lex"
ECHO;
	YY_BREAK
#line 1710 "lex.yy.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	(yy_state_ptr) = (yy_state_buf);
	*(yy_state_ptr)++ = yy_current_state;

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 274 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*(yy_state_ptr)++ = yy_current_state;
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    
	register YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 274 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 273);
	if ( ! yy_is_jam )
		*(yy_state_ptr)++ = yy_current_state;

		return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register yy_size_t number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		   
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

    (yy_state_buf) = 0;
    (yy_state_ptr) = 0;
    (yy_full_match) = 0;
    (yy_lp) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    yyfree ( (yy_state_buf) );
    (yy_state_buf)  = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 154 "decaf.lex"



  /* subroutines */

int yywrap(void) {
    return 1;  // makes it stop at EOF.
} 

int main(int argc, char **argv) {
    int tok;
    /* Make sure there's a given file name */
    if (argc != 2) {
        cout << "USAGE: " << argv[0] << " FILE" << endl;
        exit(1);
    }       
    yyin = fopen(argv[1], "r");
    /* and that it exists and can be read */
    if (!yyin) {
        cout << argv[1] << ": No such file or file can't be opened for reading." 
             << endl;
        exit(1);
    }
    /* Read tokens until finished */
    while ((tok=yylex()) != -1)
        myTok->print();

    /* there's a warning without this */
    if (false)
      yyunput(0, 0);
}

